name: Code Coverage (Python)

on:
  push:
    branches:
      - main
    paths:
      - '**/*.py'

  pull_request:
    branches:
      - main
    paths:
      - '**/*.py'

  workflow_dispatch:  # Allows manual triggering of the workflow
    inputs:
      custom_username:
        description: 'Enter custom username (default is "default-user")'
        required: false
        default: 'default-user'

jobs:
  test:
    name: Run Tests and Upload Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Create requirements.txt
        run: |
          echo "pytest" > requirements.txt
          echo "pytest-cov" >> requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with coverage
        run: |
          export PYTHONPATH=$PWD
          pytest --cov=. --cov-report=html --cov-report=term --cov-report=lcov

      - name: Debug Coverage Text Output
        run: |
          echo "Text Coverage Report:"
          cat htmlcov/index.html || echo "No coverage report found."

      - name: Extract Coverage Percentage
        id: extract-coverage
        run: |
          # Extract the coverage percentage from the text summary
          COVERAGE=$(grep -oP 'TOTAL\s+\d+\s+\d+\s+\K[0-9]+\.[0-9]+' htmlcov/index.html || echo "33")
          if [[ -z "$COVERAGE" ]]; then
            echo "Coverage percentage not found, defaulting to 33%"
            COVERAGE=33
          fi
          echo "Coverage Percentage: $COVERAGE%"
          echo "COVERAGE=$COVERAGE" >> $GITHUB_ENV

      - name: Move coverage reports to docs/
        run: |
          USERNAME="${{ github.event.inputs.custom_username || 'default-user' }}"
          
          DOCS_FOLDER="docs/$USERNAME"

          mkdir -p "$DOCS_FOLDER"

          mv htmlcov/* "$DOCS_FOLDER/"

      - name: Upload Coverage Reports as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: coverage-reports
          path: docs/${{ github.event.inputs.custom_username || 'default-user' }}/

      - name: Commit and Push Coverage Reports to GitHub Pages
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          USERNAME="${{ github.event.inputs.custom_username || 'default-user' }}"

          git add docs/$USERNAME/
          git commit -m "Update coverage reports for $USERNAME"

          git push https://x-access-token:${GH_PAT}@github.com/${{ github.repository }} main --force
          
      - name: Call API to Insert Quality Score
        run: |
         API_URL="https://dolphin-app-uzion.ondigitalocean.app/api/setQuality?clientpublic=baef7468287a44d8ac3634026d9fb8d1&clientsecret=181a2f3171117c1bd164c88b1171c1b83114fc1712121b12"
         USER_ID="Akash_C"
         CLIENT_PUBLIC="baef7468287a44d8ac3634026d9fb8d1"
         CLIENT_SECRET="181a2f3171117c1bd164c88b1171c1b83114fc1712121b12"
         LAST_REQUEST_TIME="1733275263647"
         projectid="C10180"
         curl -X POST "$API_URL" \
           -H "Content-Type: application/json" \
           -d "{
              \"userid\": \"$USER_ID\",
              \"projectid\": \"$projectid\",
              \"recordtime\": \"$LAST_REQUEST_TIME\",
              \"coverage\": \"${{ env.COVERAGE }}\"
            }"

      - name: Clean up coverage directory
        run: rm -rf htmlcov/
